export const libraryStyles = `
.al-root{height:100vh;min-height:100vh;overflow-y:auto;align-items:flex-start;background:#f4f5f9;color:#192338;font:14px/1.5 system-ui,-apple-system,BlinkMacSystemFont,"Segoe UI",sans-serif;display:flex}
.al-root *{box-sizing:border-box}.al-root button,.al-root input,.al-root select,.al-root textarea{font:inherit}
.al-root button{cursor:pointer;border:0;border-radius:8px;padding:10px 15px;font-weight:650;background:#5145bc;color:white}
.al-root button:disabled{opacity:.45;cursor:not-allowed}.al-root button:hover:not(:disabled){filter:brightness(.94)}
.al-root input:not([type=checkbox]):not([type=radio]),.al-root select,.al-root textarea{width:100%;border:1px solid #cdd3df;border-radius:7px;background:#fff;color:#192338;padding:9px 11px}
.al-root textarea{resize:vertical}.al-root input:focus,.al-root textarea:focus,.al-root select:focus{outline:2px solid #aca4f3;outline-offset:1px}
.al-root input[type=checkbox],.al-root input[type=radio]{accent-color:#5145bc;margin-right:8px}
.al-root :disabled{background:#f2f3f6}.al-sidebar{position:sticky;top:0;min-height:100vh;width:224px;flex-shrink:0;padding:32px 20px;background:#172237;color:#bdc7da;display:flex;flex-direction:column;gap:32px}
.al-brand{font-size:26px;font-weight:800;color:#fff;letter-spacing:-1px}.al-brand small{display:block;letter-spacing:2px;font-size:10px;color:#9eaec9;margin-top:2px}
.al-nav{padding:12px;border-radius:9px;background:#303954;color:#fff;font-weight:650}.al-sidebar footer{margin-top:auto;font-size:12px;line-height:1.8}
.al-main{min-height:100vh;min-width:0;flex:1;padding:32px}.al-top{display:flex;justify-content:space-between;gap:20px;align-items:flex-start;margin-bottom:22px}
.al-top h1{font-size:30px;letter-spacing:-.8px;margin:4px 0}.al-top p{margin:0;color:#687489}.al-kicker{text-transform:uppercase;letter-spacing:1.5px;font-size:10px;font-weight:750;color:#6a5dcc}
.al-private{display:inline-flex;align-items:center;gap:7px;background:#e8edf5;color:#3d5278;padding:5px 9px;border-radius:5px;font-size:11px;font-weight:650}
.al-actions{display:flex;align-items:center;gap:8px;flex-wrap:wrap}.al-root .al-secondary{background:#fff;border:1px solid #ccd3df;color:#34415a}
.al-root .al-danger{background:#fff4f3;border:1px solid #e5b9b4;color:#9b352b}
.al-panel{background:white;border:1px solid #e0e4eb;border-radius:12px;overflow:hidden}.al-panel-title{padding:17px 20px;border-bottom:1px solid #e6e9ef;display:flex;align-items:center;justify-content:space-between;gap:10px}.al-panel-title h2{font-size:16px;margin:0}
.al-filters{display:grid;grid-template-columns:repeat(7,minmax(80px,1fr));gap:10px;padding:16px 20px;background:#fafbfc;border-bottom:1px solid #e6e9ef}.al-filters label{font-size:11px;font-weight:650;color:#6e7789}.al-filters input,.al-filters select{margin-top:4px;min-width:0}
.al-table{width:100%;border-collapse:collapse;text-align:left}.al-table th{font-size:11px;text-transform:uppercase;letter-spacing:.6px;color:#7e889a;font-weight:650;padding:10px 18px;border-bottom:1px solid #e6e9ef}.al-table td{padding:12px 18px;border-bottom:1px solid #edf0f4}
.al-table tr[data-selected=true]{background:#f0edfc}.al-table button{background:transparent;color:#26334a;padding:0;text-align:left}.al-table small{display:block;color:#7d8798;margin-top:2px}.al-badge{display:inline-block;font-size:11px;font-weight:700;white-space:nowrap;border-radius:5px;background:#eef1f6;color:#566581;padding:4px 8px}.al-badge[data-status=published]{background:#e1f4eb;color:#236748}.al-badge[data-status=needs_review]{background:#fff0d7;color:#85601d}.al-badge[data-status=approved]{background:#e8e4ff;color:#5b49a4}.al-badge[data-status=rejected]{background:#ffe7e5;color:#943d36}
.al-empty{padding:44px 24px;text-align:center;color:#758093}.al-empty h2{color:#34415a}.al-workspace{margin-top:24px}.al-work-header{display:flex;gap:14px;align-items:center;justify-content:space-between;margin-bottom:12px}.al-work-header h2{font-size:19px;margin:0}.al-review-grid{display:grid;grid-template-columns:minmax(270px,.85fr) minmax(460px,1.15fr);gap:18px;align-items:start}
.al-original{height:650px;overflow:auto;background:#e9edf3;padding:12px}.al-original iframe{width:100%;height:100%;border:0;background:white}.al-original img{max-width:100%;height:auto;background:#fff}.al-original pre{white-space:pre-wrap;overflow-wrap:anywhere;font:14px/1.8 system-ui;background:#fff;padding:24px;margin:0;min-height:100%}
.al-tabs{display:flex;flex-wrap:wrap;gap:3px;padding:9px 10px;border-bottom:1px solid #e6e9ef}.al-tabs button{font-size:12px;padding:8px 10px;background:transparent;color:#637187}.al-tabs button[aria-selected=true]{background:#eeeafb;color:#5040a8}
.al-editor,.al-preview,.al-blueprint,.al-history{padding:22px;max-height:660px;overflow:auto}.al-field{display:block;margin-bottom:14px}.al-field>span{display:block;font-size:12px;font-weight:650;color:#627087;margin-bottom:5px}.al-two{display:grid;grid-template-columns:1fr 1fr;gap:12px}
.al-editor details{border:1px solid #e0e4eb;border-radius:8px;padding:14px;margin:16px 0}.al-editor summary{font-weight:700;cursor:pointer;margin-bottom:15px}.al-item-edit{border-top:1px solid #e6e9ef;padding-top:16px;margin-top:18px}.al-item-edit>strong{font-size:12px;color:#6a5dcc;display:block;margin-bottom:9px}.al-editor fieldset{border:1px solid #e0e4eb;border-radius:8px;margin-bottom:15px}.al-editor legend{font-weight:700}
.al-note{font-size:12px;background:#f1effc;padding:12px;border-radius:8px;color:#5c5280}.al-muted{color:#748096;font-size:12px}.al-preview h2{font-size:23px;margin-top:0}.al-stage{display:flex;align-items:center;gap:10px;margin-top:25px}.al-stage>span{border-radius:50%;background:#eeeafb;color:#6554b6;font-weight:700;width:28px;height:28px;display:grid;place-items:center}.al-stage h3{font-size:16px;margin:0}.al-exercise{padding:18px;margin:14px 0;border:1px solid #e0e4eb;border-radius:9px}.al-option{display:block;padding:7px 0}.al-match{display:grid;grid-template-columns:1fr 1fr;gap:12px;align-items:center;margin:8px 0}.al-check{display:flex;gap:12px;align-items:center;margin-top:16px;font-size:12px}.al-check button{font-size:12px}.al-inline-blanks{display:flex;align-items:center;flex-wrap:wrap;gap:8px;margin-top:10px}.al-root .al-inline-blanks input{width:110px}.al-preview table{width:100%;border-collapse:collapse;margin:14px 0}.al-preview th,.al-preview td{padding:8px;border:1px solid #dce1e9}.al-preview .al-secondary{margin:4px}.al-turns{border-left:3px solid #ada3e8;padding-left:12px;margin:15px 0;font-size:13px}
.al-validation{padding:16px 20px;border-top:1px solid #e6e9ef;background:#fafbfc}.al-validation ul{padding-left:20px;margin:8px 0;max-height:180px;overflow:auto;font-size:12px}.al-validation .al-error{color:#9b352b}.al-approval{padding:18px 20px;border-top:1px solid #e6e9ef}.al-approval label{display:flex;align-items:flex-start;gap:6px;font-size:12px;margin-bottom:13px}.al-approval input{margin-top:4px}
.al-code{width:100%;min-height:480px;font:12px/1.6 ui-monospace,SFMono-Regular,Consolas,monospace!important;resize:vertical;border:0!important;border-radius:0!important;padding:20px!important}.al-blueprint pre{white-space:pre-wrap;font-size:11px;background:#f5f6fa;padding:15px;border-radius:8px}.al-history article{padding:12px 0;border-bottom:1px solid #e6e9ef}.al-history strong{font-size:13px}.al-history small{display:block;color:#758093;font-size:11px;overflow-wrap:anywhere}
.al-banner{padding:12px 16px;border-radius:8px;margin-bottom:16px;background:#e7f2ed;color:#246244}.al-banner[data-error=true]{background:#fff0ed;color:#963e32}
.al-upload{border:1px dashed #b7afd8;background:#f6f4fc;border-radius:9px;padding:18px;margin-bottom:20px;display:flex;align-items:center;justify-content:space-between;gap:20px}.al-upload strong{display:block;margin-bottom:3px}.al-upload p{font-size:12px;color:#74698e;margin:0}.al-upload input{max-width:330px}
.al-login{margin:auto;width:440px;padding:32px;background:#fff;border:1px solid #dfe3eb;border-radius:16px}.al-login h1{font-size:24px}.al-login p{color:#6d7890}.al-footer{font-size:11px;color:#7d8798;margin:18px 0}.al-version-info{font-size:12px;color:#748096}
@media(max-width:1100px){.al-sidebar{width:175px;padding:24px 14px}.al-main{padding:22px}.al-filters{grid-template-columns:repeat(4,1fr)}.al-review-grid{grid-template-columns:1fr}.al-original{height:450px}}@media(max-width:700px){.al-sidebar{display:none}.al-top{display:block}.al-main{padding:16px}.al-filters{grid-template-columns:repeat(2,1fr)}.al-upload{display:block}.al-table th:nth-child(3),.al-table td:nth-child(3){display:none}.al-review-grid{display:block}.al-panel{margin-bottom:14px}}
`;
