import { useEffect } from 'react';
import { Alert, Pressable, ScrollView, StyleSheet, Text, View } from 'react-native';
import { router } from 'expo-router';
import { Ionicons } from '@expo/vector-icons';
import { Avatar, Screen } from '@/components/ui';
import { useAppStore } from '@/store/app-store';
import { colors, radius, spacing } from '@/theme/tokens';
const daysLeft=(deletedAt:string)=>Math.max(1,Math.ceil((7*24*60*60*1000-(Date.now()-new Date(deletedAt).getTime()))/(24*60*60*1000)));
export default function RecycleBin(){const deleted=useAppStore((s)=>s.deletedConversations);const characters=useAppStore((s)=>s.characters);const restore=useAppStore((s)=>s.restoreConversation);const remove=useAppStore((s)=>s.permanentlyDeleteConversation);const purge=useAppStore((s)=>s.purgeExpiredConversations);useEffect(()=>{purge()},[purge]);return <Screen><View style={styles.header}><Pressable accessibilityLabel="Back" onPress={()=>router.back()} style={styles.back}><Ionicons name="chevron-back" size={27} color={colors.ink}/></Pressable><Text style={styles.title}>Recycle Bin</Text></View><Text style={styles.note}>Chats here are permanently deleted seven days after you move them to the bin.</Text><ScrollView contentContainerStyle={styles.list}>{deleted.length===0?<View style={styles.empty}><Ionicons name="trash-outline" size={38} color={colors.muted}/><Text style={styles.emptyText}>The Recycle Bin is empty.</Text></View>:deleted.map((item)=>{const person=characters.find((character)=>character.id===item.conversation.characterId);const remaining=daysLeft(item.deletedAt);return <View key={item.conversation.id} style={styles.item}><Avatar name={person?.name??'Deleted chat'} avatarUrl={person?.avatarUrl} size={50}/><View style={styles.copy}><Text style={styles.name}>{person?.name??'Deleted chat'}</Text><Text style={styles.expires}>Deletes permanently in {remaining} day{remaining===1?'':'s'}</Text></View><Pressable accessibilityLabel="Restore chat" onPress={()=>restore(item.conversation.id)} style={styles.action}><Ionicons name="refresh" size={21} color={colors.primary}/><Text style={styles.restore}>Restore</Text></Pressable><Pressable accessibilityLabel="Delete permanently" onPress={()=>Alert.alert('Delete permanently?','This chat and all of its messages will be deleted immediately. This cannot be undone.',[{text:'Cancel',style:'cancel'},{text:'Delete permanently',style:'destructive',onPress:()=>remove(item.conversation.id)}])} style={styles.iconButton}><Ionicons name="close-circle-outline" size={23} color={colors.danger}/></Pressable></View>})}</ScrollView></Screen>}
const styles=StyleSheet.create({header:{paddingTop:54,paddingHorizontal:12,flexDirection:'row',alignItems:'center'},back:{width:44,height:44,alignItems:'center',justifyContent:'center'},title:{fontSize:27,fontWeight:'800',color:colors.ink},note:{marginHorizontal:spacing.lg,marginTop:12,fontSize:14,lineHeight:20,color:colors.muted},list:{padding:spacing.md,paddingBottom:40},item:{backgroundColor:colors.surface,borderRadius:radius.lg,padding:spacing.md,marginBottom:10,flexDirection:'row',alignItems:'center'},copy:{flex:1,marginLeft:12},name:{fontSize:16,fontWeight:'800',color:colors.ink},expires:{fontSize:12,color:colors.muted,marginTop:3},action:{alignItems:'center',padding:7},restore:{fontSize:10,fontWeight:'700',color:colors.primary},iconButton:{padding:7},empty:{alignItems:'center',marginTop:90,gap:12},emptyText:{fontSize:15,color:colors.muted}});

