process.on('uncaughtException', e => { console.error(e.message, e.code ?? '', e.where ?? ''); process.exit(1); });
import { createRequire } from 'node:module';
import { readFile } from 'node:fs/promises';
import assert from 'node:assert/strict';
const require = createRequire(process.env.PGLITE_PACKAGE + '/package.json');
const { PGlite } = require('@electric-sql/pglite');
const db = new PGlite();
await db.exec(`
create role anon; create role authenticated; create role service_role;
create schema auth; create schema storage;
create table auth.users(id uuid primary key);
create function auth.uid() returns uuid language sql as $$ select nullif(current_setting('request.jwt.claim.sub',true),'')::uuid $$;
grant usage on schema auth to authenticated,service_role;
create table storage.buckets(id text primary key,name text,public boolean,file_size_limit bigint,allowed_mime_types text[]);
create table storage.objects(id uuid primary key default gen_random_uuid(),bucket_id text,name text,created_at timestamptz not null default now(),unique(bucket_id,name));
create function storage.foldername(text) returns text[] language sql as $$ select string_to_array($1,'/') $$;
`);
const base = (await readFile('supabase/migrations/202608230001_initial_schema.sql','utf8')).replace(/create extension if not exists (pgcrypto|vector);/g,'').replace('vector(1536)','text');
await db.exec(base);
await db.exec(await readFile('supabase/migrations/202609060001_durable_ai_reply_delivery.sql','utf8'));
await db.exec(`alter table public.profiles add column is_premium boolean default false,add column premium_expires_at timestamptz,add column trial_ends_at timestamptz,add column grace_period_ends_at timestamptz;`);
await db.exec(await readFile('supabase/migrations/202609080001_audio_and_conversation_retention.sql','utf8'));
const user='10000000-0000-4000-8000-000000000001', other='10000000-0000-4000-8000-000000000002';
const character='20000000-0000-4000-8000-000000000001', conversation='30000000-0000-4000-8000-000000000001';
const message='40000000-0000-4000-8000-000000000001', assessment='50000000-0000-4000-8000-000000000001';
await db.exec(`
insert into auth.users values('${user}'),('${other}');
insert into characters(id,user_id,name,date_of_birth,relationship_type) values('${character}','${user}','Test','1990-01-01','friend');
insert into conversations(id,user_id,character_id,created_at) values('${conversation}','${user}','${character}',now()-interval '7 months');
insert into messages(id,conversation_id,user_id,sender,kind,created_at) values('${message}','${conversation}','${user}','user','voice',now()-interval '7 months');
insert into voice_messages(message_id,user_id,storage_path,duration_ms,created_at) values('${message}','${user}','${user}/old.m4a',1000,now()-interval '7 months');
insert into storage.objects(bucket_id,name,created_at) values('voice-notes','${user}/old.m4a',now()-interval '7 months');
insert into language_assessments(id,user_id,message_id) values('${assessment}','${user}','${message}');
insert into corrections(assessment_id,category,original_text,improved_text) values('${assessment}','grammar','I goes','I go');
insert into pronunciation_assessments(user_id,voice_message_id,provider) values('${user}','${message}','test');
insert into academic_records values('${user}','tutor:test','{}',now()-interval '2 years');
select retention_purge_history(500);
`);
assert.equal((await db.query('select count(*)::int as n from messages')).rows[0].n,1,'keep DB references until storage deletion');
await db.exec(`delete from storage.objects; select retention_purge_history(500);`);
assert.equal((await db.query('select count(*)::int as n from messages')).rows[0].n,0);
assert.equal((await db.query('select count(*)::int as n from conversations')).rows[0].n,0);
assert.equal((await db.query('select count(*)::int as n from corrections')).rows[0].n,1);
assert.equal((await db.query('select message_id from language_assessments')).rows[0].message_id,null);
assert.equal((await db.query('select voice_message_id from pronunciation_assessments')).rows[0].voice_message_id,null);
assert.equal((await db.query('select count(*)::int as n from academic_records')).rows[0].n,1);
await db.exec("insert into storage.objects(bucket_id,name) select 'voice-notes','page/'||n from generate_series(1,205) n;");
let after=null, visited=0;
while(true) {
 const {rows}=await db.query('select * from retention_audio_page($1,100)',[after]);
 if(!rows.length)break;
 visited+=rows.length; after=rows.at(-1).object_id;
 for(const row of rows)await db.query('delete from storage.objects where id=$1',[row.object_id]);
}
assert.equal(visited,205,'no pagination skips while deleting objects');
const token='60000000-0000-4000-8000-000000000001';
assert.equal((await db.query('select retention_acquire($1) as ok',[token])).rows[0].ok,true);
assert.equal((await db.query('select retention_acquire($1) as ok',[other])).rows[0].ok,false);
await db.query('select retention_release($1)',[token]);
await db.exec(`set role authenticated; select set_config('request.jwt.claim.sub','${user}',false);`);
assert.equal((await db.query('select can_export_conversations() as ok')).rows[0].ok,false);
await assert.rejects(db.query('select retention_purge_history(500)'));
await assert.rejects(db.query("select register_user_audio_age($1,now())",[other+'/private.m4a']));
assert.equal((await db.query('select count(*)::int as n from academic_records')).rows[0].n,1);
await db.exec(`select set_config('request.jwt.claim.sub','${other}',false);`);
assert.equal((await db.query('select count(*)::int as n from academic_records')).rows[0].n,0);
await db.exec(`reset role; update profiles set is_premium=true where id='${user}'; set role authenticated; select set_config('request.jwt.claim.sub','${user}',false);`);
assert.equal((await db.query('select can_export_conversations() as ok')).rows[0].ok,true);
await db.exec(`reset role; update profiles set premium_expires_at=now()-interval '1 second' where id='${user}'; set role authenticated;`);
assert.equal((await db.query('select can_export_conversations() as ok')).rows[0].ok,false);
await db.close();
console.log('PostgreSQL checks passed: academic preservation, storage ordering, pagination, lease, premium expiry, ownership.');
