import type { InterfaceLocale } from "@/domain/models";

type Copy={title:string;definition:string;fiction:string;limits:string};
export const aiDisclosureCopy:Record<InterfaceLocale,Copy>={
  en:{title:"Fersons are AI",definition:"“Ferson” means “fake person.”",fiction:"Every Ferson is a fictional, AI-generated contact created for language practice.",limits:"They are not real people, cannot act in the real world, and should not be relied on for professional or emergency advice."},
  "es-419":{title:"Los Fersons son IA",definition:"“Ferson” significa “fake person”: persona falsa.",fiction:"Cada Ferson es un contacto ficticio generado por IA para practicar idiomas.",limits:"No son personas reales, no pueden actuar en el mundo real y no deben sustituir consejos profesionales ni ayuda de emergencia."},
  "es-ES":{title:"Los Fersons son IA",definition:"“Ferson” significa “fake person”: persona falsa.",fiction:"Cada Ferson es un contacto ficticio generado por IA para practicar idiomas.",limits:"No son personas reales, no pueden actuar en el mundo real y no deben sustituir consejos profesionales ni ayuda de emergencia."},
  "pt-BR":{title:"Os Fersons são IA",definition:"“Ferson” significa “fake person”: pessoa falsa.",fiction:"Cada Ferson é um contato fictício gerado por IA para praticar idiomas.",limits:"Eles não são pessoas reais, não podem agir no mundo real e não substituem orientação profissional ou ajuda de emergência."},
  "zh-Hans":{title:"Ferson 是 AI",definition:"“Ferson”源自“fake person”，意为虚拟人物。",fiction:"每个 Ferson 都是为语言练习而生成的虚构 AI 联系人。",limits:"他们不是真人，无法在现实世界中行动，也不能替代专业建议或紧急援助。"},
  ja:{title:"Ferson はAIです",definition:"「Ferson」は「fake person（架空の人物）」という意味です。",fiction:"すべての Ferson は、語学練習のためにAIが生成した架空の連絡相手です。",limits:"実在の人物ではなく、現実世界で行動できません。専門的な助言や緊急時の支援の代わりにはなりません。"},
  ko:{title:"Ferson은 AI예요",definition:"“Ferson”은 “fake person”, 즉 가상의 사람이라는 뜻이에요.",fiction:"모든 Ferson은 언어 연습을 위해 AI가 만든 가상의 연락 상대예요.",limits:"실제 사람이 아니며 현실에서 행동할 수 없고, 전문적인 조언이나 긴급 지원을 대신할 수 없어요."},
  vi:{title:"Ferson là AI",definition:"“Ferson” có nghĩa là “fake person”: một người hư cấu.",fiction:"Mỗi Ferson là một người liên hệ hư cấu do AI tạo ra để luyện ngôn ngữ.",limits:"Họ không phải người thật, không thể hành động ngoài đời và không thay thế tư vấn chuyên môn hoặc hỗ trợ khẩn cấp."},
  id:{title:"Ferson adalah AI",definition:"“Ferson” berarti “fake person”: orang rekaan.",fiction:"Setiap Ferson adalah kontak fiktif buatan AI untuk latihan bahasa.",limits:"Mereka bukan orang sungguhan, tidak dapat bertindak di dunia nyata, dan tidak menggantikan nasihat profesional atau bantuan darurat."},
  ar:{title:"شخصيات Ferson تعمل بالذكاء الاصطناعي",definition:"تعني كلمة “Ferson” شخصًا خياليًا أو مزيفًا.",fiction:"كل Ferson جهة اتصال خيالية ينشئها الذكاء الاصطناعي لممارسة اللغة.",limits:"ليست شخصيات حقيقية ولا يمكنها التصرف في العالم الواقعي، ولا تغني عن المشورة المهنية أو المساعدة الطارئة."},
  fr:{title:"Les Fersons sont des IA",definition:"« Ferson » signifie « fake person » : une personne fictive.",fiction:"Chaque Ferson est un contact fictif généré par l’IA pour pratiquer une langue.",limits:"Ce ne sont pas de vraies personnes, elles ne peuvent pas agir dans le monde réel et ne remplacent ni un avis professionnel ni une aide d’urgence."},
  tr:{title:"Fersonlar yapay zekâdır",definition:"“Ferson”, “fake person”, yani kurgusal kişi anlamına gelir.",fiction:"Her Ferson, dil pratiği için yapay zekâ tarafından oluşturulan kurgusal bir kişidir.",limits:"Gerçek kişiler değildir, gerçek dünyada hareket edemezler ve profesyonel tavsiye ya da acil yardım yerine kullanılamazlar."},
};
