import type { InterfaceLocale } from '@/domain/models';

type AuthCopy = {
  createTitle:string; signInTitle:string; createSubtitle:string; signInSubtitle:string;
  password:string; create:string; signIn:string; or:string; google:string; apple:string;
  existing:string; newHere:string; verifyTitle:string; verifyIntro:string; code:string;
  verify:string; resend:string; sending:string; different:string; resent:string;
};

export const authCopy: Record<InterfaceLocale, AuthCopy> = {
  en:{createTitle:'Create your account',signInTitle:'Welcome back',createSubtitle:'Save your Fersons and continue on any device.',signInSubtitle:'Sign in to continue your conversations.',password:'Password (8+ characters)',create:'Create account',signIn:'Sign in',or:'or',google:'Continue with Google',apple:'Continue with Apple',existing:'Already have an account? Sign in',newHere:'New here? Create an account',verifyTitle:'Verify your email',verifyIntro:'Enter the verification code sent to',code:'Verification code',verify:'Verify email',resend:'Resend code',sending:'Sending…',different:'Use a different email',resent:'A new verification code was sent.'},
  'es-419':{createTitle:'Crea tu cuenta',signInTitle:'Qué bueno verte de nuevo',createSubtitle:'Guarda tus Fersons y continúa en cualquier dispositivo.',signInSubtitle:'Inicia sesión para continuar tus conversaciones.',password:'Contraseña (8+ caracteres)',create:'Crear cuenta',signIn:'Iniciar sesión',or:'o',google:'Continuar con Google',apple:'Continuar con Apple',existing:'¿Ya tienes una cuenta? Inicia sesión',newHere:'¿Eres nuevo? Crea una cuenta',verifyTitle:'Verifica tu correo',verifyIntro:'Ingresa el código de verificación enviado a',code:'Código de verificación',verify:'Verificar correo',resend:'Reenviar código',sending:'Enviando…',different:'Usar otro correo',resent:'Se envió un nuevo código de verificación.'},
  'es-ES':{createTitle:'Crea tu cuenta',signInTitle:'Qué bien verte de nuevo',createSubtitle:'Guarda tus Fersons y continúa en cualquier dispositivo.',signInSubtitle:'Inicia sesión para continuar tus conversaciones.',password:'Contraseña (8+ caracteres)',create:'Crear cuenta',signIn:'Iniciar sesión',or:'o',google:'Continuar con Google',apple:'Continuar con Apple',existing:'¿Ya tienes una cuenta? Inicia sesión',newHere:'¿Eres nuevo? Crea una cuenta',verifyTitle:'Verifica tu correo',verifyIntro:'Introduce el código de verificación enviado a',code:'Código de verificación',verify:'Verificar correo',resend:'Reenviar código',sending:'Enviando…',different:'Usar otro correo',resent:'Se ha enviado un nuevo código de verificación.'},
  'pt-BR':{createTitle:'Crie sua conta',signInTitle:'Boas-vindas de volta',createSubtitle:'Salve seus Fersons e continue em qualquer dispositivo.',signInSubtitle:'Entre para continuar suas conversas.',password:'Senha (8+ caracteres)',create:'Criar conta',signIn:'Entrar',or:'ou',google:'Continuar com Google',apple:'Continuar com Apple',existing:'Já tem uma conta? Entre',newHere:'É novo por aqui? Crie uma conta',verifyTitle:'Verifique seu e-mail',verifyIntro:'Digite o código de verificação enviado para',code:'Código de verificação',verify:'Verificar e-mail',resend:'Reenviar código',sending:'Enviando…',different:'Usar outro e-mail',resent:'Um novo código de verificação foi enviado.'},
  'zh-Hans':{createTitle:'创建账户',signInTitle:'欢迎回来',createSubtitle:'保存你的 Ferson，并在任何设备上继续。',signInSubtitle:'登录以继续对话。',password:'密码（至少 8 个字符）',create:'创建账户',signIn:'登录',or:'或',google:'使用 Google 继续',apple:'使用 Apple 继续',existing:'已有账户？登录',newHere:'第一次使用？创建账户',verifyTitle:'验证电子邮箱',verifyIntro:'输入发送至此邮箱的验证码：',code:'验证码',verify:'验证邮箱',resend:'重新发送验证码',sending:'正在发送…',different:'使用其他邮箱',resent:'新的验证码已发送。'},
  ja:{createTitle:'アカウントを作成',signInTitle:'おかえりなさい',createSubtitle:'Fersonを保存して、どの端末からでも続けられます。',signInSubtitle:'ログインして会話を続けましょう。',password:'パスワード（8文字以上）',create:'アカウントを作成',signIn:'ログイン',or:'または',google:'Googleで続ける',apple:'Appleで続ける',existing:'アカウントをお持ちですか？ログイン',newHere:'初めてですか？アカウントを作成',verifyTitle:'メールを確認',verifyIntro:'次のアドレスに送信された確認コードを入力してください：',code:'確認コード',verify:'メールを確認',resend:'コードを再送信',sending:'送信中…',different:'別のメールを使う',resent:'新しい確認コードを送信しました。'},
  ko:{createTitle:'계정 만들기',signInTitle:'다시 오신 것을 환영합니다',createSubtitle:'Ferson을 저장하고 어느 기기에서든 계속하세요.',signInSubtitle:'로그인하여 대화를 계속하세요.',password:'비밀번호(8자 이상)',create:'계정 만들기',signIn:'로그인',or:'또는',google:'Google로 계속',apple:'Apple로 계속',existing:'계정이 있나요? 로그인',newHere:'처음이신가요? 계정 만들기',verifyTitle:'이메일 인증',verifyIntro:'다음 주소로 보낸 인증 코드를 입력하세요:',code:'인증 코드',verify:'이메일 인증',resend:'코드 다시 보내기',sending:'보내는 중…',different:'다른 이메일 사용',resent:'새 인증 코드를 보냈습니다.'},
  vi:{createTitle:'Tạo tài khoản',signInTitle:'Chào mừng trở lại',createSubtitle:'Lưu các Ferson và tiếp tục trên mọi thiết bị.',signInSubtitle:'Đăng nhập để tiếp tục trò chuyện.',password:'Mật khẩu (từ 8 ký tự)',create:'Tạo tài khoản',signIn:'Đăng nhập',or:'hoặc',google:'Tiếp tục với Google',apple:'Tiếp tục với Apple',existing:'Đã có tài khoản? Đăng nhập',newHere:'Bạn mới dùng? Tạo tài khoản',verifyTitle:'Xác minh email',verifyIntro:'Nhập mã xác minh đã gửi đến',code:'Mã xác minh',verify:'Xác minh email',resend:'Gửi lại mã',sending:'Đang gửi…',different:'Dùng email khác',resent:'Mã xác minh mới đã được gửi.'},
  id:{createTitle:'Buat akun',signInTitle:'Selamat datang kembali',createSubtitle:'Simpan Ferson Anda dan lanjutkan di perangkat apa pun.',signInSubtitle:'Masuk untuk melanjutkan percakapan.',password:'Kata sandi (8+ karakter)',create:'Buat akun',signIn:'Masuk',or:'atau',google:'Lanjutkan dengan Google',apple:'Lanjutkan dengan Apple',existing:'Sudah punya akun? Masuk',newHere:'Baru di sini? Buat akun',verifyTitle:'Verifikasi email',verifyIntro:'Masukkan kode verifikasi yang dikirim ke',code:'Kode verifikasi',verify:'Verifikasi email',resend:'Kirim ulang kode',sending:'Mengirim…',different:'Gunakan email lain',resent:'Kode verifikasi baru telah dikirim.'},
  ar:{createTitle:'إنشاء حسابك',signInTitle:'مرحبًا بعودتك',createSubtitle:'احفظ شخصيات Ferson وتابع من أي جهاز.',signInSubtitle:'سجّل الدخول لمتابعة محادثاتك.',password:'كلمة المرور (8 أحرف فأكثر)',create:'إنشاء حساب',signIn:'تسجيل الدخول',or:'أو',google:'المتابعة باستخدام Google',apple:'المتابعة باستخدام Apple',existing:'لديك حساب؟ سجّل الدخول',newHere:'مستخدم جديد؟ أنشئ حسابًا',verifyTitle:'تحقق من بريدك الإلكتروني',verifyIntro:'أدخل رمز التحقق المرسل إلى',code:'رمز التحقق',verify:'تحقق من البريد',resend:'إعادة إرسال الرمز',sending:'جارٍ الإرسال…',different:'استخدام بريد آخر',resent:'تم إرسال رمز تحقق جديد.'},
  fr:{createTitle:'Créez votre compte',signInTitle:'Bon retour',createSubtitle:'Enregistrez vos Fersons et continuez sur n’importe quel appareil.',signInSubtitle:'Connectez-vous pour poursuivre vos conversations.',password:'Mot de passe (8 caractères minimum)',create:'Créer un compte',signIn:'Se connecter',or:'ou',google:'Continuer avec Google',apple:'Continuer avec Apple',existing:'Vous avez déjà un compte ? Connectez-vous',newHere:'Nouveau ici ? Créez un compte',verifyTitle:'Vérifiez votre e-mail',verifyIntro:'Saisissez le code de vérification envoyé à',code:'Code de vérification',verify:'Vérifier l’e-mail',resend:'Renvoyer le code',sending:'Envoi…',different:'Utiliser un autre e-mail',resent:'Un nouveau code de vérification a été envoyé.'},
  tr:{createTitle:'Hesabını oluştur',signInTitle:'Tekrar hoş geldin',createSubtitle:'Fersonlarını kaydet ve istediğin cihazdan devam et.',signInSubtitle:'Sohbetlerine devam etmek için giriş yap.',password:'Şifre (en az 8 karakter)',create:'Hesap oluştur',signIn:'Giriş yap',or:'veya',google:'Google ile devam et',apple:'Apple ile devam et',existing:'Zaten hesabın var mı? Giriş yap',newHere:'Yeni misin? Hesap oluştur',verifyTitle:'E-postanı doğrula',verifyIntro:'Şu adrese gönderilen doğrulama kodunu gir:',code:'Doğrulama kodu',verify:'E-postayı doğrula',resend:'Kodu yeniden gönder',sending:'Gönderiliyor…',different:'Başka bir e-posta kullan',resent:'Yeni bir doğrulama kodu gönderildi.'},
};
