import type { InterfaceLocale } from "@/domain/models";

export const interestIds = ["music","movies","travel","food","sports","books","games","technology","art","nature","work","family"] as const;
type InterestId = typeof interestIds[number];
type Copy = { title:string; body:string; optional:string; labels:Record<InterestId,string> };
const en: Copy={title:"What do you like talking about?",body:"Choose a few interests. Your Fersons can use them to start conversations that feel relevant to you.",optional:"Optional — choose as many as you like",labels:{music:"Music",movies:"Movies & TV",travel:"Travel",food:"Food",sports:"Sports",books:"Books",games:"Games",technology:"Technology",art:"Art",nature:"Nature",work:"Work",family:"Family & friends"}};
const es: Copy={title:"¿De qué te gusta hablar?",body:"Elige algunos intereses. Tus Fersons podrán usarlos para iniciar conversaciones relevantes para ti.",optional:"Opcional — elige cuantos quieras",labels:{music:"Música",movies:"Cine y series",travel:"Viajes",food:"Comida",sports:"Deportes",books:"Libros",games:"Juegos",technology:"Tecnología",art:"Arte",nature:"Naturaleza",work:"Trabajo",family:"Familia y amigos"}};
export const interestsCopy: Record<InterfaceLocale,Copy>={
  en,"es-419":es,"es-ES":es,
  "pt-BR":{title:"Sobre o que você gosta de conversar?",body:"Escolha alguns interesses. Seus Fersons poderão usá-los para iniciar conversas relevantes para você.",optional:"Opcional — escolha quantos quiser",labels:{music:"Música",movies:"Filmes e séries",travel:"Viagens",food:"Comida",sports:"Esportes",books:"Livros",games:"Jogos",technology:"Tecnologia",art:"Arte",nature:"Natureza",work:"Trabalho",family:"Família e amigos"}},
  "zh-Hans":{title:"你喜欢聊什么？",body:"选择几个兴趣。你的 Ferson 可以用它们开启更贴近你的对话。",optional:"可选——可多选",labels:{music:"音乐",movies:"影视",travel:"旅行",food:"美食",sports:"运动",books:"书籍",games:"游戏",technology:"科技",art:"艺术",nature:"自然",work:"工作",family:"家人与朋友"}},
  ja:{title:"どんな話題が好きですか？",body:"興味のあるものを選ぶと、Ferson があなたに合う会話を始めやすくなります。",optional:"任意・複数選択可",labels:{music:"音楽",movies:"映画・テレビ",travel:"旅行",food:"食べ物",sports:"スポーツ",books:"本",games:"ゲーム",technology:"テクノロジー",art:"アート",nature:"自然",work:"仕事",family:"家族・友人"}},
  ko:{title:"어떤 이야기를 좋아하세요?",body:"관심사를 몇 개 선택하면 Ferson이 나에게 맞는 대화를 시작할 수 있어요.",optional:"선택 사항 · 여러 개 선택 가능",labels:{music:"음악",movies:"영화·TV",travel:"여행",food:"음식",sports:"스포츠",books:"책",games:"게임",technology:"기술",art:"예술",nature:"자연",work:"일",family:"가족·친구"}},
  vi:{title:"Bạn thích trò chuyện về điều gì?",body:"Chọn vài sở thích để Ferson có thể bắt đầu những cuộc trò chuyện phù hợp với bạn.",optional:"Không bắt buộc — chọn bao nhiêu tùy thích",labels:{music:"Âm nhạc",movies:"Phim ảnh",travel:"Du lịch",food:"Ẩm thực",sports:"Thể thao",books:"Sách",games:"Trò chơi",technology:"Công nghệ",art:"Nghệ thuật",nature:"Thiên nhiên",work:"Công việc",family:"Gia đình và bạn bè"}},
  id:{title:"Kamu suka membicarakan apa?",body:"Pilih beberapa minat agar Ferson dapat memulai percakapan yang relevan bagimu.",optional:"Opsional — pilih sebanyak yang kamu suka",labels:{music:"Musik",movies:"Film & TV",travel:"Perjalanan",food:"Makanan",sports:"Olahraga",books:"Buku",games:"Gim",technology:"Teknologi",art:"Seni",nature:"Alam",work:"Pekerjaan",family:"Keluarga & teman"}},
  ar:{title:"ما المواضيع التي تحب التحدث عنها؟",body:"اختر بعض الاهتمامات ليتمكن Ferson من بدء محادثات تناسبك.",optional:"اختياري — اختر ما تشاء",labels:{music:"الموسيقى",movies:"الأفلام والتلفزيون",travel:"السفر",food:"الطعام",sports:"الرياضة",books:"الكتب",games:"الألعاب",technology:"التقنية",art:"الفن",nature:"الطبيعة",work:"العمل",family:"العائلة والأصدقاء"}},
  fr:{title:"De quoi aimez-vous parler ?",body:"Choisissez quelques centres d’intérêt. Vos Fersons pourront s’en servir pour lancer des conversations qui vous correspondent.",optional:"Facultatif — choisissez-en autant que vous voulez",labels:{music:"Musique",movies:"Films et séries",travel:"Voyages",food:"Cuisine",sports:"Sports",books:"Livres",games:"Jeux",technology:"Technologie",art:"Art",nature:"Nature",work:"Travail",family:"Famille et amis"}},
  tr:{title:"Neler hakkında konuşmayı seversin?",body:"Birkaç ilgi alanı seç. Fersonların sana uygun sohbetler başlatmak için bunları kullanabilir.",optional:"İsteğe bağlı — istediğin kadar seç",labels:{music:"Müzik",movies:"Film ve dizi",travel:"Seyahat",food:"Yemek",sports:"Spor",books:"Kitaplar",games:"Oyunlar",technology:"Teknoloji",art:"Sanat",nature:"Doğa",work:"İş",family:"Aile ve arkadaşlar"}},
};
