import type { InterfaceLocale } from '@/domain/models';

interface LearningFactSet { title: string; facts: string[] }

export const learningFacts: Record<InterfaceLocale, LearningFactSet> = {
  en: { title: 'While you wait', facts: ['Actively recalling a word strengthens memory more than simply rereading it.', 'Short practice sessions spread across several days usually beat one long study session.', 'Sleep helps the brain consolidate newly learned words and patterns.', 'Meaningful conversation trains both understanding and producing language at the same time.'] },
  'es-419': { title: 'Mientras esperas', facts: ['Recordar una palabra activamente fortalece más la memoria que simplemente volver a leerla.', 'Las prácticas cortas repartidas durante varios días suelen funcionar mejor que una sola sesión larga.', 'Dormir ayuda al cerebro a consolidar palabras y patrones recién aprendidos.', 'Una conversación significativa entrena al mismo tiempo la comprensión y la producción del idioma.'] },
  'es-ES': { title: 'Mientras esperas', facts: ['Recordar una palabra activamente fortalece más la memoria que simplemente volver a leerla.', 'Las prácticas cortas repartidas durante varios días suelen funcionar mejor que una sola sesión larga.', 'Dormir ayuda al cerebro a consolidar palabras y patrones recién aprendidos.', 'Una conversación significativa entrena al mismo tiempo la comprensión y la producción del idioma.'] },
  'pt-BR': { title: 'Enquanto você espera', facts: ['Lembrar ativamente uma palavra fortalece mais a memória do que apenas relê-la.', 'Práticas curtas distribuídas por vários dias costumam funcionar melhor do que uma única sessão longa.', 'O sono ajuda o cérebro a consolidar palavras e padrões recém-aprendidos.', 'Uma conversa significativa treina ao mesmo tempo a compreensão e a produção do idioma.'] },
  'zh-Hans': { title: '等待时了解一下', facts: ['主动回想一个词，比单纯重复阅读更能巩固记忆。', '分散在几天内的短时练习，通常比一次长时间学习更有效。', '睡眠有助于大脑巩固新学到的词汇和语言模式。', '有意义的对话可以同时训练语言理解和表达能力。'] },
  ja: { title: '待っている間に', facts: ['単語をただ読み返すより、積極的に思い出す方が記憶に定着しやすくなります。', '数日間に分けた短い練習は、一度の長時間学習より効果的なことが多いです。', '睡眠は、新しく学んだ単語やパターンを脳に定着させるのに役立ちます。', '意味のある会話では、理解する力と表現する力を同時に鍛えられます。'] },
  ko: { title: '기다리는 동안', facts: ['단어를 반복해서 읽기보다 직접 떠올리는 연습이 기억을 더 잘 강화합니다.', '며칠에 걸쳐 짧게 연습하는 것이 한 번에 오래 공부하는 것보다 대체로 효과적입니다.', '수면은 새로 배운 단어와 언어 패턴을 뇌가 정리하고 기억하는 데 도움을 줍니다.', '의미 있는 대화는 언어를 이해하는 능력과 표현하는 능력을 동시에 훈련합니다.'] },
  vi: { title: 'Trong khi chờ', facts: ['Chủ động nhớ lại một từ giúp củng cố trí nhớ tốt hơn là chỉ đọc lại từ đó.', 'Các buổi luyện tập ngắn trải đều trong nhiều ngày thường hiệu quả hơn một buổi học dài.', 'Giấc ngủ giúp não bộ củng cố những từ và mẫu ngôn ngữ mới học.', 'Hội thoại có ý nghĩa rèn luyện đồng thời khả năng hiểu và diễn đạt ngôn ngữ.'] },
  id: { title: 'Sambil menunggu', facts: ['Mengingat sebuah kata secara aktif memperkuat ingatan lebih baik daripada sekadar membacanya ulang.', 'Latihan singkat yang tersebar selama beberapa hari biasanya lebih efektif daripada satu sesi panjang.', 'Tidur membantu otak menyimpan kata dan pola bahasa yang baru dipelajari.', 'Percakapan bermakna melatih pemahaman dan kemampuan menghasilkan bahasa secara bersamaan.'] },
  ar: { title: 'في أثناء الانتظار', facts: ['استرجاع الكلمة من الذاكرة بنشاط يقوّي تذكّرها أكثر من مجرد إعادة قراءتها.', 'جلسات التدريب القصيرة الموزعة على عدة أيام تكون عادةً أفضل من جلسة طويلة واحدة.', 'يساعد النوم الدماغ على تثبيت الكلمات والأنماط اللغوية الجديدة.', 'يدرّب الحوار الهادف فهم اللغة واستخدامها في الوقت نفسه.'] },
  fr: { title: 'Pendant votre attente', facts: ['Se rappeler activement un mot renforce davantage la mémoire que le simple fait de le relire.', 'De courtes séances réparties sur plusieurs jours sont généralement plus efficaces qu’une seule longue séance.', 'Le sommeil aide le cerveau à consolider les mots et les structures nouvellement appris.', 'Une conversation porteuse de sens entraîne à la fois la compréhension et la production de la langue.'] },
  tr: { title: 'Beklerken', facts: ['Bir kelimeyi aktif olarak hatırlamak, onu yalnızca tekrar okumaktan daha güçlü bir hafıza oluşturur.', 'Birkaç güne yayılan kısa çalışmalar genellikle tek bir uzun çalışmadan daha etkilidir.', 'Uyku, beynin yeni öğrenilen kelimeleri ve dil kalıplarını pekiştirmesine yardımcı olur.', 'Anlamlı sohbet, dili anlama ve üretme becerilerini aynı anda çalıştırır.'] },
};
