import type { InterfaceLocale } from "@/domain/models";

type PrivacyCopy = { title: string; privateData: string; technicalData: string };

export const privacyCopy: Record<InterfaceLocale, PrivacyCopy> = {
  en: { title: "Your privacy", privateData: "Your private conversations, voice messages, personal details, and sign-in information are never included in crash reports or app-usage insights.", technicalData: "Ferson only uses privacy-safe technical information to keep the app reliable and understand which features are useful." },
  "es-419": { title: "Tu privacidad", privateData: "Tus conversaciones privadas, mensajes de voz, datos personales e información de inicio de sesión nunca se incluyen en informes de errores ni en estadísticas de uso.", technicalData: "Ferson solo usa información técnica respetuosa con tu privacidad para mantener la aplicación estable y saber qué funciones son útiles." },
  "es-ES": { title: "Tu privacidad", privateData: "Tus conversaciones privadas, mensajes de voz, datos personales e información de inicio de sesión nunca se incluyen en informes de errores ni en estadísticas de uso.", technicalData: "Ferson solo usa información técnica respetuosa con tu privacidad para mantener la aplicación estable y saber qué funciones son útiles." },
  "pt-BR": { title: "Sua privacidade", privateData: "Suas conversas privadas, mensagens de voz, dados pessoais e informações de acesso nunca são incluídos em relatórios de erros nem em análises de uso.", technicalData: "A Ferson usa apenas informações técnicas que preservam sua privacidade para manter o app confiável e entender quais recursos são úteis." },
  "zh-Hans": { title: "你的隐私", privateData: "你的私人对话、语音消息、个人资料和登录信息绝不会出现在崩溃报告或应用使用分析中。", technicalData: "Ferson 只使用不涉及隐私的技术信息来保障应用稳定，并了解哪些功能有用。" },
  ja: { title: "プライバシー", privateData: "非公開の会話、音声メッセージ、個人情報、ログイン情報が、クラッシュ報告や利用状況の分析に含まれることはありません。", technicalData: "Ferson は、アプリの安定性を保ち、役立つ機能を把握するために、プライバシーに配慮した技術情報のみを使用します。" },
  ko: { title: "개인정보 보호", privateData: "비공개 대화, 음성 메시지, 개인정보 및 로그인 정보는 오류 보고서나 앱 사용 분석에 절대 포함되지 않습니다.", technicalData: "Ferson은 앱을 안정적으로 유지하고 유용한 기능을 파악하기 위해 개인정보를 침해하지 않는 기술 정보만 사용합니다." },
  vi: { title: "Quyền riêng tư của bạn", privateData: "Cuộc trò chuyện riêng tư, tin nhắn thoại, thông tin cá nhân và thông tin đăng nhập của bạn không bao giờ được đưa vào báo cáo lỗi hoặc phân tích sử dụng ứng dụng.", technicalData: "Ferson chỉ dùng thông tin kỹ thuật an toàn cho quyền riêng tư để giữ ứng dụng ổn định và hiểu tính năng nào hữu ích." },
  id: { title: "Privasimu", privateData: "Percakapan pribadi, pesan suara, data pribadi, dan informasi masukmu tidak pernah disertakan dalam laporan kerusakan atau analisis penggunaan aplikasi.", technicalData: "Ferson hanya menggunakan informasi teknis yang aman bagi privasi untuk menjaga keandalan aplikasi dan memahami fitur yang berguna." },
  ar: { title: "خصوصيتك", privateData: "لا تُضمَّن محادثاتك الخاصة أو رسائلك الصوتية أو بياناتك الشخصية أو معلومات تسجيل الدخول في تقارير الأعطال أو إحصاءات استخدام التطبيق مطلقًا.", technicalData: "تستخدم Ferson معلومات تقنية آمنة للخصوصية فقط للحفاظ على موثوقية التطبيق ومعرفة الميزات المفيدة." },
  fr: { title: "Votre vie privée", privateData: "Vos conversations privées, messages vocaux, données personnelles et informations de connexion ne figurent jamais dans les rapports d’erreur ni dans les analyses d’utilisation.", technicalData: "Ferson utilise uniquement des informations techniques respectueuses de votre vie privée pour assurer la fiabilité de l’application et comprendre quelles fonctions sont utiles." },
  tr: { title: "Gizliliğin", privateData: "Özel konuşmaların, sesli mesajların, kişisel bilgilerin ve oturum açma bilgilerin hata raporlarına veya uygulama kullanım analizlerine hiçbir zaman eklenmez.", technicalData: "Ferson, uygulamayı güvenilir tutmak ve hangi özelliklerin yararlı olduğunu anlamak için yalnızca gizliliği koruyan teknik bilgileri kullanır." },
};
