import type { InterfaceLocale } from "@/domain/models";

type PrivacyCopy = { title: string; privateData: string; technicalData: string };

export const privacyCopy: Record<InterfaceLocale, PrivacyCopy> = {
  en: { title: "Your privacy", privateData: "Your private conversations, voice messages, personal details, and sign-in information are never included in crash reports or app-usage insights.", technicalData: "Ferson uses limited, privacy-safe technical information to keep the app reliable and fix problems." },
  "es-419": { title: "Tu privacidad", privateData: "Tus conversaciones privadas, mensajes de voz, datos personales e información de inicio de sesión nunca se incluyen en informes de errores ni en estadísticas de uso.", technicalData: "Ferson usa información técnica limitada y respetuosa con tu privacidad para mantener la aplicación estable y solucionar problemas." },
  "es-ES": { title: "Tu privacidad", privateData: "Tus conversaciones privadas, mensajes de voz, datos personales e información de inicio de sesión nunca se incluyen en informes de errores ni en estadísticas de uso.", technicalData: "Ferson usa información técnica limitada y respetuosa con tu privacidad para mantener la aplicación estable y solucionar problemas." },
  "pt-BR": { title: "Sua privacidade", privateData: "Suas conversas privadas, mensagens de voz, dados pessoais e informações de acesso nunca são incluídos em relatórios de erros nem em análises de uso.", technicalData: "A Ferson usa informações técnicas limitadas e seguras para manter o app confiável e corrigir problemas." },
  "zh-Hans": { title: "你的隐私", privateData: "你的私人对话、语音消息、个人资料和登录信息绝不会出现在崩溃报告或应用使用分析中。", technicalData: "Ferson 仅使用有限且不涉及隐私的技术信息来保持应用稳定并修复问题。" },
  ja: { title: "プライバシー", privateData: "非公開の会話、音声メッセージ、個人情報、ログイン情報が、クラッシュ報告や利用状況の分析に含まれることはありません。", technicalData: "Ferson は、アプリの安定性を保ち問題を修正するため、プライバシーに配慮した必要最小限の技術情報のみを使用します。" },
  ko: { title: "개인정보 보호", privateData: "비공개 대화, 음성 메시지, 개인정보 및 로그인 정보는 오류 보고서나 앱 사용 분석에 절대 포함되지 않습니다.", technicalData: "Ferson은 앱을 안정적으로 유지하고 문제를 해결하기 위해 개인정보를 침해하지 않는 최소한의 기술 정보만 사용합니다." },
  vi: { title: "Quyền riêng tư của bạn", privateData: "Cuộc trò chuyện riêng tư, tin nhắn thoại, thông tin cá nhân và thông tin đăng nhập của bạn không bao giờ được đưa vào báo cáo lỗi hoặc phân tích sử dụng ứng dụng.", technicalData: "Ferson chỉ dùng thông tin kỹ thuật giới hạn và an toàn cho quyền riêng tư để giữ ứng dụng ổn định và khắc phục sự cố." },
  id: { title: "Privasimu", privateData: "Percakapan pribadi, pesan suara, data pribadi, dan informasi masukmu tidak pernah disertakan dalam laporan kerusakan atau analisis penggunaan aplikasi.", technicalData: "Ferson hanya menggunakan informasi teknis terbatas yang aman bagi privasi untuk menjaga keandalan aplikasi dan memperbaiki masalah." },
  ar: { title: "خصوصيتك", privateData: "لا تُضمَّن محادثاتك الخاصة أو رسائلك الصوتية أو بياناتك الشخصية أو معلومات تسجيل الدخول في تقارير الأعطال أو إحصاءات استخدام التطبيق مطلقًا.", technicalData: "تستخدم Ferson قدرًا محدودًا من المعلومات التقنية الآمنة للخصوصية للحفاظ على موثوقية التطبيق وإصلاح المشكلات." },
  fr: { title: "Votre vie privée", privateData: "Vos conversations privées, messages vocaux, données personnelles et informations de connexion ne figurent jamais dans les rapports d’erreur ni dans les analyses d’utilisation.", technicalData: "Ferson utilise des informations techniques limitées et respectueuses de votre vie privée pour assurer la fiabilité de l’application et corriger les problèmes." },
  tr: { title: "Gizliliğin", privateData: "Özel konuşmaların, sesli mesajların, kişisel bilgilerin ve oturum açma bilgilerin hata raporlarına veya uygulama kullanım analizlerine hiçbir zaman eklenmez.", technicalData: "Ferson, uygulamayı güvenilir tutmak ve sorunları gidermek için gizliliği koruyan sınırlı teknik bilgiler kullanır." },
};

export const voiceRetentionCopy: Record<InterfaceLocale, string> = {
  "en": "After 15 days, voice messages are compressed to lower quality. Audio and conversation messages are permanently deleted after six months on every plan. Academic records and Tutor corrections are kept without a time limit. Conversation export is available with Premium.",
  "es-419": "Después de 15 días, los mensajes de voz se comprimen con menor calidad. El audio y los mensajes de conversación se eliminan permanentemente a los seis meses en todos los planes. Los registros académicos y las correcciones del Tutor se conservan sin límite de tiempo. La exportación de conversaciones está disponible con Premium.",
  "es-ES": "Después de 15 días, los mensajes de voz se comprimen con menor calidad. El audio y los mensajes de conversación se eliminan permanentemente a los seis meses en todos los planes. Los registros académicos y las correcciones del Tutor se conservan sin límite de tiempo. La exportación de conversaciones está disponible con Premium.",
  "pt-BR": "Após 15 dias, as mensagens de voz são comprimidas com qualidade reduzida. O áudio e as mensagens das conversas são excluídos permanentemente após seis meses em todos os planos. Os registros acadêmicos e as correções do Tutor são mantidos sem limite de tempo. A exportação de conversas está disponível no Premium.",
  "zh-Hans": "语音消息在15天后压缩为较低音质。所有套餐的音频和聊天消息均在六个月后永久删除。学习记录和导师纠正记录不限时保留。Premium用户可导出聊天记录。",
  "ja": "音声メッセージは15日後に低音質へ圧縮されます。すべてのプランで音声と会話メッセージは6か月後に完全に削除されます。学習記録とTutorの添削は期限なく保存されます。会話のエクスポートはPremiumで利用できます。",
  "ko": "음성 메시지는 15일 후 낮은 음질로 압축됩니다. 모든 요금제에서 음성과 대화 메시지는 6개월 후 영구 삭제됩니다. 학습 기록과 Tutor 교정은 기간 제한 없이 보관됩니다. 대화 내보내기는 Premium에서 이용할 수 있습니다.",
  "vi": "Sau 15 ngày, tin nhắn thoại được nén xuống chất lượng thấp hơn. Âm thanh và tin nhắn hội thoại bị xóa vĩnh viễn sau sáu tháng ở mọi gói. Hồ sơ học tập và phần sửa lỗi của Tutor được giữ không giới hạn thời gian. Xuất hội thoại dành cho Premium.",
  "id": "Setelah 15 hari, pesan suara dikompresi ke kualitas lebih rendah. Audio dan pesan percakapan dihapus permanen setelah enam bulan di semua paket. Catatan belajar dan koreksi Tutor disimpan tanpa batas waktu. Ekspor percakapan tersedia dengan Premium.",
  "ar": "بعد 15 يومًا، تُضغط الرسائل الصوتية بجودة أقل. يُحذف الصوت ورسائل المحادثة نهائيًا بعد ستة أشهر في جميع الخطط. تُحفظ السجلات التعليمية وتصحيحات Tutor دون حد زمني. تصدير المحادثات متاح مع Premium.",
  "fr": "Après 15 jours, les messages vocaux sont compressés avec une qualité réduite. Les fichiers audio et les messages sont supprimés définitivement après six mois pour toutes les offres. Les dossiers d’apprentissage et les corrections du Tutor sont conservés sans limite de durée. L’exportation des conversations est disponible avec Premium.",
  "tr": "Sesli mesajlar 15 gün sonra daha düşük kalitede sıkıştırılır. Tüm planlarda ses ve sohbet mesajları altı ay sonra kalıcı olarak silinir. Öğrenme kayıtları ve Tutor düzeltmeleri süre sınırı olmadan saklanır. Sohbet dışa aktarma Premium ile kullanılabilir."
};
