create extension if not exists pgcrypto;
create extension if not exists vector;

create type public.message_kind as enum ('text','voice','system');
create type public.message_sender as enum ('user','character');
create type public.subscription_status as enum ('trialing','active','past_due','canceled','expired');

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  interface_language text not null default 'en', support_language text not null default 'en', target_language text not null default 'en' check (target_language='en'),
  english_level text, pronunciation_target text not null default 'general-american', correction_intensity text not null default 'balanced', timezone text not null default 'UTC', country_code text,
  voice_processing_consent_at timestamptz, onboarding_completed_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table public.characters (
  id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, name text not null, date_of_birth date not null,
  relationship_type text not null, location jsonb not null default '{}', biography jsonb not null default '{}', personality jsonb not null default '{}', communication_style jsonb not null default '{}', voice_identity jsonb not null default '{}', avatar_path text,
  generation_prompt_version text, archived_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create index characters_user_idx on public.characters(user_id) where archived_at is null;
create table public.character_life_state (character_id uuid primary key references public.characters(id) on delete cascade, mood text, current_concerns jsonb not null default '[]', current_projects jsonb not null default '[]', future_intentions jsonb not null default '[]', updated_at timestamptz not null default now());
create table public.character_life_events (id uuid primary key default gen_random_uuid(), character_id uuid not null references public.characters(id) on delete cascade, event_type text not null, content jsonb not null, starts_at timestamptz, ends_at timestamptz, status text not null default 'planned', created_at timestamptz not null default now());
create index life_events_character_time_idx on public.character_life_events(character_id, starts_at desc);
create table public.character_connections (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, character_a_id uuid not null references public.characters(id) on delete cascade, character_b_id uuid not null references public.characters(id) on delete cascade, relationship_type text not null, relationship_state jsonb not null default '{}', unique(character_a_id, character_b_id), check(character_a_id<>character_b_id));
create table public.revealed_character_facts (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, character_id uuid not null references public.characters(id) on delete cascade, fact_key text not null, revealed_value jsonb not null, revealed_at timestamptz not null default now(), source_message_id uuid, unique(user_id, character_id, fact_key));

create table public.conversations (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, character_id uuid not null references public.characters(id) on delete cascade, unread_count int not null default 0, last_message_at timestamptz, summary text, summary_through timestamptz, created_at timestamptz not null default now(), unique(user_id, character_id));
create index conversations_inbox_idx on public.conversations(user_id, last_message_at desc);
create table public.messages (id uuid primary key default gen_random_uuid(), conversation_id uuid not null references public.conversations(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, sender message_sender not null, kind message_kind not null, body text, status text not null default 'sent', client_id uuid, reply_to_id uuid references public.messages(id) on delete set null, provider_metadata jsonb not null default '{}', created_at timestamptz not null default now(), deleted_at timestamptz, unique(user_id, client_id));
create index messages_timeline_idx on public.messages(conversation_id, created_at desc) where deleted_at is null;
alter table public.revealed_character_facts add constraint revealed_source_fk foreign key(source_message_id) references public.messages(id) on delete set null;
create table public.voice_messages (message_id uuid primary key references public.messages(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, storage_path text not null, duration_ms int not null check(duration_ms>0), waveform jsonb, transcription text, transcription_status text not null default 'pending', pronunciation_status text not null default 'pending', processing_error text, created_at timestamptz not null default now());

create table public.memories (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, character_id uuid references public.characters(id) on delete cascade, conversation_id uuid references public.conversations(id) on delete cascade, memory_type text not null, content text not null, structured_content jsonb not null default '{}', confidence real not null check(confidence between 0 and 1), importance real not null default .5 check(importance between 0 and 1), source_message_id uuid references public.messages(id) on delete set null, supersedes_id uuid references public.memories(id) on delete set null, valid_until timestamptz, deleted_at timestamptz, created_at timestamptz not null default now(), updated_at timestamptz not null default now());
create index memories_retrieval_idx on public.memories(user_id, character_id, memory_type) where deleted_at is null;
create table public.memory_embeddings (memory_id uuid primary key references public.memories(id) on delete cascade, embedding vector(1536) not null, model text not null, created_at timestamptz not null default now());

create table public.learner_profiles (user_id uuid primary key references public.profiles(id) on delete cascade, estimated_cefr text, grammar_summary jsonb not null default '{}', vocabulary_summary jsonb not null default '{}', speaking_summary jsonb not null default '{}', updated_at timestamptz not null default now());
create table public.language_assessments (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, message_id uuid references public.messages(id) on delete cascade, proficiency_signals jsonb not null default '[]', overall_confidence real, created_at timestamptz not null default now());
create table public.corrections (id uuid primary key default gen_random_uuid(), assessment_id uuid not null references public.language_assessments(id) on delete cascade, category text not null, original_text text not null, improved_text text not null, explanation jsonb, severity smallint not null default 1, dismissed_at timestamptz, opened_at timestamptz, created_at timestamptz not null default now());
create table public.phonemes (id uuid primary key default gen_random_uuid(), target_language text not null default 'en', ipa text not null, category text not null, articulation jsonb not null, learner_explanations jsonb not null default '{}', animation_asset_id text, unique(target_language, ipa));
create table public.pronunciation_assessments (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, voice_message_id uuid not null references public.voice_messages(message_id) on delete cascade, provider text not null, provider_version text, pronunciation_score real, fluency_score real, intelligibility_score real, stress_score real, prosody_score real, raw_result jsonb, created_at timestamptz not null default now());
create table public.pronunciation_segments (id uuid primary key default gen_random_uuid(), assessment_id uuid not null references public.pronunciation_assessments(id) on delete cascade, segment_type text not null check(segment_type in ('sentence','word','phoneme')), position int not null, text text, phoneme_id uuid references public.phonemes(id), score real, metrics jsonb not null default '{}');

create table public.subscriptions (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, store text not null, original_transaction_id text not null, product_id text not null, plan_key text not null, status subscription_status not null, trial_ends_at timestamptz, current_period_starts_at timestamptz, current_period_ends_at timestamptz, country_code text, platform text, updated_at timestamptz not null default now(), unique(store, original_transaction_id));
create index subscriptions_user_status_idx on public.subscriptions(user_id,status);
create table public.subscription_events (id uuid primary key default gen_random_uuid(), subscription_id uuid references public.subscriptions(id) on delete set null, user_id uuid not null references public.profiles(id) on delete cascade, store_event_id text not null unique, event_type text not null, amount_minor bigint, currency text, effective_at timestamptz not null, payload jsonb not null default '{}', received_at timestamptz not null default now());
create table public.analytics_events (id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles(id) on delete set null, anonymous_id uuid, event_name text not null, session_id uuid, properties jsonb not null default '{}', occurred_at timestamptz not null, received_at timestamptz not null default now());
create index analytics_event_time_idx on public.analytics_events(event_name,occurred_at desc);
create table public.ai_usage (id uuid primary key default gen_random_uuid(), user_id uuid references public.profiles(id) on delete set null, conversation_id uuid references public.conversations(id) on delete set null, provider text not null, model text not null, feature text not null, request_id text, input_tokens int, output_tokens int, audio_seconds numeric(10,3), estimated_cost_usd numeric(14,8) not null default 0, latency_ms int, success boolean not null, error_code text, created_at timestamptz not null default now());
create index ai_usage_cost_idx on public.ai_usage(user_id,created_at desc);
create table public.notification_preferences (user_id uuid primary key references public.profiles(id) on delete cascade, enabled boolean not null default true, quiet_hours jsonb, character_initiation_frequency text not null default 'normal', updated_at timestamptz not null default now());
create table public.generated_notifications (id uuid primary key default gen_random_uuid(), user_id uuid not null references public.profiles(id) on delete cascade, character_id uuid references public.characters(id) on delete cascade, kind text not null, title text not null, body text not null, scheduled_for timestamptz not null, sent_at timestamptz, canceled_at timestamptz, rationale jsonb not null default '{}', created_at timestamptz not null default now());

alter table public.profiles enable row level security; alter table public.characters enable row level security; alter table public.character_life_state enable row level security; alter table public.character_life_events enable row level security; alter table public.character_connections enable row level security; alter table public.revealed_character_facts enable row level security; alter table public.conversations enable row level security; alter table public.messages enable row level security; alter table public.voice_messages enable row level security; alter table public.memories enable row level security; alter table public.memory_embeddings enable row level security; alter table public.learner_profiles enable row level security; alter table public.language_assessments enable row level security; alter table public.corrections enable row level security; alter table public.pronunciation_assessments enable row level security; alter table public.pronunciation_segments enable row level security; alter table public.subscriptions enable row level security; alter table public.subscription_events enable row level security; alter table public.analytics_events enable row level security; alter table public.ai_usage enable row level security; alter table public.notification_preferences enable row level security; alter table public.generated_notifications enable row level security;

create policy "own profiles" on public.profiles for all using(id=auth.uid()) with check(id=auth.uid());
create policy "own characters" on public.characters for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own conversations" on public.conversations for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own messages" on public.messages for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own voice" on public.voice_messages for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own memories" on public.memories for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own learner profile" on public.learner_profiles for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own assessments" on public.language_assessments for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own pronunciation" on public.pronunciation_assessments for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own subscriptions read" on public.subscriptions for select using(user_id=auth.uid());
create policy "own subscription events read" on public.subscription_events for select using(user_id=auth.uid());
create policy "own analytics insert" on public.analytics_events for insert with check(user_id=auth.uid());
create policy "own notification preferences" on public.notification_preferences for all using(user_id=auth.uid()) with check(user_id=auth.uid());
create policy "own generated notifications" on public.generated_notifications for select using(user_id=auth.uid());

insert into storage.buckets(id,name,public,file_size_limit,allowed_mime_types) values('voice-notes','voice-notes',false,26214400,array['audio/m4a','audio/mp4','audio/mpeg','audio/wav','audio/webm']) on conflict(id) do nothing;
create policy "voice owner insert" on storage.objects for insert to authenticated with check(bucket_id='voice-notes' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "voice owner read" on storage.objects for select to authenticated using(bucket_id='voice-notes' and (storage.foldername(name))[1]=auth.uid()::text);
create policy "voice owner delete" on storage.objects for delete to authenticated using(bucket_id='voice-notes' and (storage.foldername(name))[1]=auth.uid()::text);

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id) values(new.id); insert into public.notification_preferences(user_id) values(new.id); insert into public.learner_profiles(user_id) values(new.id); return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
